name: check-paths
on:
  push:
    branches:
#      - main
    paths: 
      - 'src/*.c'
  pull_request:
    paths: 
      - 'src/*.c'
     
jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello'
